function [tDraw] = drawRespArray(respArray,cursorPos,cursorColour,globals)


% Draw the textures and borders to backbuffer
for iPos = 1:numel(respArray)
    Screen('DrawTexture',...
        globals.window,...
        respArray(1,iPos),...
        [],...
        globals.xyEdgesResp(:,iPos));
end

% Draw the frames for the images to the screen back buffer
% The cursor is not zero indexed
Screen('FrameRect',...
        globals.window,...
        cursorColour,...
        globals.xyEdgesResp(:,(cursorPos)),...
        globals.penWidthPixels)

% Flip the screen
tDraw = Screen('Flip', globals.window, globals.t);
%Screen('Close', texture) % close the texture so it doesnt ' hang around' as PTB warns

return